---
- name: Ensure a user can use Github as an external IdP
  hosts: ipaserver
  become: false
  gather_facts: false
  vars:
    github_login: tscherf

  tasks:
  - name: Retrieve Gitbhub user id
    ansible.builtin.uri:
      url: "https://api.github.com/users/{{ github_login }}"
      method: GET
      headers:
        Accept: "application/vnd.github.v3+json"
    register: user_data

  - name: Ensure user exists with IdP configuration
    freeipa.ansible_freeipa.ipauser:
      ipaadmin_password: "{{ ipa_admin_password }}"
      name: tscherf
      first: Thorsten
      last: Scherf
      userauthtype: idp
      idp: github_idp
      idp_user_id: "{{ user_data.json.id }}"
